# Generated by Django 6.0.4 on 2026-05-06 23:17

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="SymptomLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("logged_at", models.DateTimeField(auto_now_add=True)),
                (
                    "pain_level",
                    models.PositiveSmallIntegerField(
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(10),
                        ]
                    ),
                ),
                (
                    "stress_level",
                    models.PositiveSmallIntegerField(
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(10),
                        ]
                    ),
                ),
                (
                    "hydration_level",
                    models.PositiveSmallIntegerField(
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(10),
                        ]
                    ),
                ),
                (
                    "pain_location",
                    models.CharField(
                        choices=[
                            ("chest", "Chest"),
                            ("abdomen", "Abdomen"),
                            ("back", "Back"),
                            ("joints", "Joints"),
                            ("head", "Head"),
                            ("other", "Other"),
                        ],
                        max_length=20,
                    ),
                ),
                ("fatigue", models.BooleanField(default=False)),
                ("shortness_of_breath", models.BooleanField(default=False)),
                ("dizziness", models.BooleanField(default=False)),
                ("fever", models.BooleanField(default=False)),
                ("jaundice", models.BooleanField(default=False)),
                ("swelling", models.BooleanField(default=False)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="symptom_logs",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-logged_at"],
            },
        ),
    ]
