# Generated by Django 6.0.4 on 2026-04-18 01:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("authentication", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="genotype",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
